# Generated by Django 3.2.7 on 2024-04-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='AdminAccount',
            field=models.BooleanField(default=False),
        ),
    ]
